name: purple_lints
description: List of strict linter rules that can be used both in Dart and Flutter projects to enforce a highly maintainable style.
repository: https://github.com/purplenoodlesoop/purple_lints/tree/master/packages/purple_lints
version: 0.1.1

environment:
  sdk: '>=2.12.0 <3.0.0'